services:
  api:
    user: "${HOST_UID}:${HOST_GID}"
    build: ./apps/api
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - ./apps/api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    user: "${HOST_UID}:${HOST_GID}"
    build: ./apps/api
    command: celery -A core worker -l info --concurrency=1 -O fair
    env_file: .env
    volumes:
      - ./apps/api:/code
    depends_on:
      - api
      - redis
      - db

  beat:
    user: "${HOST_UID}:${HOST_GID}"
    build: ./apps/api
    command: celery -A core beat -l info
    env_file: .env
    volumes:
      - ./apps/api:/code
    depends_on:
      - api
      - redis
      - db

  db:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pg: {}
