# Generated by Django 5.2.7 on 2025-10-18 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("exchange", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ABOVE", "Crosses Above"),
                            ("BELOW", "Crosses Below"),
                            ("PCT_UP", "Percent Up"),
                            ("PCT_DOWN", "Percent Down"),
                        ],
                        max_length=16,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "reference",
                    models.CharField(
                        choices=[
                            ("PREV_CLOSE", "Previous Close"),
                            ("SESSION_OPEN", "Session Open"),
                        ],
                        default="PREV_CLOSE",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="market.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=140)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.ticker"
                    ),
                ),
                (
                    "watchlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="market.watchlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=140)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="market.alert",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["triggered_at"], name="market_aler_trigger_feb4f3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(db_index=True)),
                ("open", models.DecimalField(decimal_places=4, max_digits=12)),
                ("high", models.DecimalField(decimal_places=4, max_digits=12)),
                ("low", models.DecimalField(decimal_places=4, max_digits=12)),
                ("close", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.ticker"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "ts"], name="market_pric_ticker__c55f7c_idx"
                    )
                ],
                "unique_together": {("ticker", "ts")},
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["user", "ticker", "is_active"],
                name="market_aler_user_id_a99277_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["ticker", "kind", "is_active"],
                name="market_aler_ticker__e44297_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                fields=("user", "ticker", "kind", "threshold", "reference"),
                name="uniq_user_ticker_kind_threshold_reference",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="watchlistitem",
            unique_together={("watchlist", "ticker")},
        ),
    ]
